spring:
  application:
    name: dt-ms-three-clientsAndPayers

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-beanilku-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 2025

externalService:
  dt-ms-one-clients:
    api: https://distributed-tracing-ms-one-beanilku-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/clients
  dt-ms-two-payers:
    api: https://distributed-tracing-ms-two-beanilku-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/payers

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

