spring:
  application:
    name: dt-ms-two-payers

  datasource:
    url: jdbc:h2:mem:testdb
    username: sq
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect


management:
  zipkin:
    tracing:
      endpoint: https://zipkin-beanilku-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 2024

externalService:
  dt-ms-one-clients:
    url: https://distributed-tracing-ms-one-beanilku-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/clients/

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

