spring:
  application:
    name: dt-ms-two-payers

  datasource:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6633051
    username: sql6633051
    password: mRyDxYeTGc
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


management:
  zipkin:
    tracing:
      endpoint: https://zipkin-beanilku-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 2024

externalService:
  dt-ms-one-clients:
    url: http://localhost:2023/clients/

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

